---
abstract: 'Fetch mail from the cloud using webservices'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::wsgetmail
name: App-wsgetmail
no_index:
  directory:
    - inc
    - t
requires:
  Azure::AD::ClientCredentials: 0
  Clone: 0
  File::Slurp: 0
  File::Temp: 0
  FindBin: 0
  Getopt::Long: 0
  IPC::Run: 0
  JSON: 0
  LWP::UserAgent: '6.42'
  Module::Load: 0
  Moo: 0
  Pod::Usage: 0
  Test::LWP::UserAgent: 0
  Test::More: 0
  URI: 0
  URI::Escape: 0
  perl: 5.10.0
  strict: 0
  warnings: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '0.09'
